### ISSUE TITLE
Make clear what kind of files are being downloaded in the manifest

### ISSUE THREAD

**Issue by malloryfreeberg** [DataBiosphere/data-browser#307] opened 2018-10-26 14:10 UTC
Similar to issue #305 , when I click "Request File Manifest", I am shown a list of file extensions with what I think are file counts and total sizes.

1. Value for FILES (78.5k) is much larger than the sum of what I think are file counts in the middle column (342 files I summed from the example below)
1. I have no idea what type of information is in files such as those with csv, txt, results, tsv, pdf, jpeg, unknown, etc.
1. Why are there file extensions (last 3) with no size? are they empty? do they not exist?

- - -
![screen shot 2018-10-26 at 15 05 22](https://user-images.githubusercontent.com/10993501/47571642-f4971600-d930-11e8-88a4-c82a94748934.png)

┆Issue Number: HCAB-270

**Comment by hannes-ucsc** [comment] 2018-10-26 17:56
These are three different issues in one.

Item 2. seems like a near duplicate of #305.

@NoopDog, @malloryfreeberg, would you be ok with moving item 2 to #305 and splitting this up into two tickets?

**Comment by malloryfreeberg** [comment] 2018-10-29 11:57
Will do.

**Comment by malloryfreeberg** [comment] 2018-10-29 12:02
1. Added as ticket #317 
1. Updated in ticket #305 
1. Added as ticket #318

**Closed as completed** 2018-10-29 21:32 UTC
