### ISSUE TITLE
Fix - Download Dialog issues

### ISSUE THREAD

**Issue by kozbo** [DataBiosphere/data-browser#225] opened 2018-08-31 20:13 UTC
Collecting a few different issues here for simplicity
 - [ ] Having a long list of file types causes the last lint of text to be cut off "These files are"...
 - [ ] Sizes are confusing and don't equal the amount shown as the total
 - [ ] Selecting certain file types does not change the manifest created

┆Issue Number: HCAB-205

**Comment by NoopDog** [comment] 2018-09-03 02:52
@kozbo can you send us a screen shot of the first one (last line of text to be cut off) also can you go to https://www.whatsmybrowser.org/ and add a screen shot of the info. This will help reproduce this issue. (also what environment did yo see this in?

**Comment by NoopDog** [comment] 2018-09-06 03:39
I have opened 3 Azul tickets  to address the root cause of these:

* File Facet List and File Summary do not have the Same File Types on Dev (Size of "unknown" file type is not in /file/summary)#297
https://app.zenhub.com/workspace/o/databiosphere/azul/issues/297



* Total File Size is Only Including the fastq.gz File Types in the files/summary API#298
https://app.zenhub.com/workspace/o/databiosphere/azul/issues/298


* File Format is Ignored When Responding to /repository/files/export to generate Manifest#299
https://app.zenhub.com/workspace/o/databiosphere/azul/issues/299


I also created
https://app.zenhub.com/workspace/o/humancellatlas/data-browser/issues/229

To make us more robust to the missing "unknown" file type in the summary.

**Comment by theathorn** [comment] 2018-09-06 22:54
Tracked in 3 separate tickets - closing.

**Closed as completed by theathorn** 2018-09-06 22:54 UTC
