### ISSUE TITLE
Make the diagrams on site be readable 

### ISSUE THREAD

**Issue by gabsie** [DataBiosphere/data-browser#824] opened 2019-08-20 17:21 UTC
The diagrams as they appear now in the browser are really not readable. I think two things can be done, maybe:
They maybe need to be in some svg format, and see if this improves the readability
Have an extra link to open up in a pop-up in bigger size so that a person can see them bigger

Cheers!
Gabs

**Comment by diekhans** [comment] 2019-08-20 18:35
Random thoughts from someone obsessed with not having fuzzy images..

SVG, as a vector format, will yield the best results!!  

However, people who are graphics-challenged and may want to use
it in a paper might have trouble with the conversion.  Having a
link to a PDF would give both a vector format and something more
people know how to deal with.  I am not sure this is even important

It may help to make the PNG somewhat larger.  When I open image
in a new tab it is a bit bigger, but is still hard to read.

If there is some kind of popup, it would be good if it is not blocked
by normal popup blocked and to still allow opening image in
another tab.

**Comment by NoopDog** [comment] 2019-08-20 19:14
This is a dupe of https://app.zenhub.com/workspaces/dcp-5ac7bcf9465cb172b77760d9/issues/humancellatlas/data-portal/485

Closing

**Closed as completed by NoopDog** 2019-08-20 19:14 UTC

**Comment by gabsie** [comment] 2019-08-20 19:51
Hi, Mark @diekhans 

I think the primary aim is to understand and perceive the diagram as you are browsing on the web, so the quality and the options should satisfy this first, without having to open up an additional PDF file.

The secondary aim of using in a paper (if we consider this likely) etc can be accomplished additionally, through a secondary link, etc

p.s. they already look much better as PNG-s. but an additional bigger size would be great!

All best,
Gabs

**Comment by diekhans** [comment] 2019-08-20 20:03
Agreed on web view being the priority.  Sometimes, when I have though reading, maybe on a small screen, I like to be able to zoom image. Would be good to  be sure this is possible,
