### ISSUE TITLE
AnVIL: display "Donors" and "Files" counts above their respective selection tabs

### ISSUE THREAD

**Issue by theathorn** [DataBiosphere/data-browser#2908] opened 2022-10-26 18:53 UTC
The Donors and Files counts on the upper right could be positioned directly above the selection tabs on the left of the same name. Unsure as to how the "Species" count should be handled in this instance, but the redundant use of "Donors" and "Files" seems unintuitive.

![image.png](https://images.zenhubusercontent.com/5ae772614b5806bc2bd13821/e6257af3-c475-4b89-a721-926108125d55)

**Comment by MillenniumFalconMechanic** [comment] 2023-05-19 20:04
Dupe of https://github.com/DataBiosphere/data-browser/issues/3322.

**Closed as not planned by MillenniumFalconMechanic** 2023-05-19 20:04 UTC
