### ISSUE TITLE
Bulk download project-level matrix and metadata

### ISSUE THREAD

**Issue by matthewspeir** [DataBiosphere/data-browser#911] opened 2019-10-02 18:16 UTC
**User story:**

> As a portal developer, I would like to download the matrix and metadata for each project in the DCP in one step (i.e. without having to click the download icon for each dataset) so that I can import these projects into my portal. I also do not want to download this data as a single concatenated matrix containing all projects.

From the recent usability testing feedback.

One idea: Make the metadata and matrix files linked on the Explore > Projects page available in the 'Get Data' flow.

**Comment by maximilianh** [comment] 2019-10-07 13:15
There are many ways this could be solved. I bet there already is a way to get the list of project IDs somehow though the DSS API or some other mechanism. If you could simply document that or give us external developers an idea how we could potentially get these, that would be great. 

The use case here is solved by "mget" in ftp, so this is not an uncommon request. Once I have the list of project IDs, I can iterate over them and download all the matrix + meta data files.  

Maybe I'm just missing a link to the right API, and this is not about the DSS API but some other API, I'm still a bit naive when it comes to HCA APIs, there seem to be a few different ones.

The more general version of this question is if there is a way to get the list of projects and their meta data, exactly what is shown at https://data.humancellatlas.org/explore/projects . Is the source code of https://data.humancellatlas.org/explore/projects available somewhere? @DailyDreaming @NoopDog  ?

At https://dss.data.humancellatlas.org/ I can only find files and bundles, but I am interested in projects. So maybe this is not the right API and the page "explore/projects" uses some other backend to show this table?

**Comment by fabdavid** [comment] 2019-10-07 17:28
You can get a JSON containing all projects and associated metadata from there:
https://service.explore.data.humancellatlas.org/repository/projects

**Comment by maximilianh** [comment] 2019-10-07 17:30
Great, so there is an API for this! Thanks Fabrice!

**Comment by theathorn** [comment] 2019-10-07 17:34
The documentation of the API used by the Data Browser is a  work in progress under DataBiosphere/azul#710.

**Comment by hannes-ucsc** [comment] 2019-10-08 05:15
@maximilianh, It's worth noting that the endpoint @fabdavid posted only gets you selected metadata, the properties that we deem important.

@matthewspeir 

> One idea: Make the metadata and matrix files linked on the Explore > Projects page available in the 'Get Data' flow.

We must have been thinking along the same lines. Getting the full manifest for all projects in one TSV is covered by https://github.com/HumanCellAtlas/data-browser/issues/912.

With respect to getting the complete matrix, you'd have to file a ticket with the matrix service. I don't think there is anything we can do here. If I am right, we can close this as a dupe of #912. Do you agree?

**Comment by maximilianh** [comment] 2019-10-08 06:36
Hi Hannes, yes, it may be a subset of properties, but a subset is a whole
lot better than nothing. :-)

To explain why this is not a minor feature: the lack of this small
functionality makes it impossible for all red boxes in the world to show
anything, to do what they promised, no one can really reliably show HCA
data right now. People can show various databases, GEO or EBI, but not HCA.
All it takes to change this is documenting this endpoint.

**Comment by matthewspeir** [comment] 2019-10-17 10:10
@hannes-ucsc 
>With respect to getting the complete matrix, you'd have to file a ticket with the matrix service. I don't think there is anything we can do here. If I am right, we can close this as a dupe of #912. Do you agree?

I thought that we linked pre-generated matrices per project from the Explore > Projects page? I guess I was imagining making those available through the manifest as well.

**Comment by hannes-ucsc** [comment] 2019-10-17 16:58
@matthewspeir

> I thought that we linked pre-generated matrices per project from the Explore > Projects page?

That's correct. But MS generates them.

> I guess I was imagining making those available through the manifest as well.

In the manifest, we can only provide files that are stored in the DSS. MS would have to place them there by submitting a special matrix bundle to the DSS. I think would be a good idea but you would have to request this from them.

**Comment by maximilianh** [comment] 2019-10-17 18:47
If they’re not stored in the DSS, where are they stored then ??

**Comment by hannes-ucsc** [comment] 2019-10-17 18:55
They are stored on the DB's project assets bucket.

**Comment by hannes-ucsc** [comment] 2019-10-17 18:56
DB = Data Browser

**Comment by maximilianh** [comment] 2019-10-17 19:03
MS=Microsoft ? :-)

Ok I guess it’s “matrix service”...?

So there are files in the DCP that are impossible to get with the command
line client.

Is that bucket open so I can list it? I could then use an S3 tool for the
download instead of reverse engineering the data browser API.

**Comment by hannes-ucsc** [comment] 2019-10-17 20:44
> Ok I guess it’s “matrix service”...?

Yes. 

> So there are files in the DCP that are impossible to get with the command
line client.

Correct.

> Is that bucket open so I can list it? 

Not sure, but it should be straight-forward to find out. The bucket name is `project-assets.data.humancellatlas.org`. The bucket is exposed via CloudFront and the public URLs are derived from the project UUID: 

https://data.humancellatlas.org/project-assets/project-matrices/008e40e8-66ae-43bb-951c-c073a2fa6774.csv.zip

Listing project UUIDs with Azul: 

```
$ http https://service.explore.data.humancellatlas.org/repository/projects?size=100 | jq .hits[].entryId
"74b6d569-3b11-42ef-b6b1-a0454522b4a0"
"f86f1ab4-1fbb-4510-ae35-3ffd752d4dfc"
"1defdada-a365-44ad-9b29-443b06bd11d6"
"4a95101c-9ffc-4f30-a809-f04518a23803"
"8185730f-4113-40d3-9cc3-929271784c2b"
"005d611a-14d5-4fbf-846e-571a1f874f70"
"a29952d9-925e-40f4-8a1c-274f118f1f51"
"f81efc03-9f56-4354-aabb-6ce819c3d414"
"cc95ff89-2e68-4a08-a234-480eca21ce79"
"a9c022b4-c771-4468-b769-cabcf9738de3"
"4d6f6c96-2a83-43d8-8fe1-0f53bffd4674"
"008e40e8-66ae-43bb-951c-c073a2fa6774"
"c4077b3c-5c98-4d26-a614-246d12c2e5d7"
"8c3c290d-dfff-4553-8868-54ce45f4ba7f"
"90bd6933-40c0-48d4-8d76-778c103bf545"
"091cf39b-01bc-42e5-9437-f419a66c8a45"
"f83165c5-e2ea-4d15-a5cf-33f3550bffde"
"027c51c6-0719-469f-a7f5-640fe57cbece"
"116965f3-f094-4769-9d28-ae675c1b569c"
"cddab57b-6868-4be4-806f-395ed9dd635a"
"2043c65a-1cf8-4828-a656-9e247d4e64f1"
"ae71be1d-ddd8-4feb-9bed-24c3ddb6e1ad"
"abe1a013-af7a-45ed-8c26-f3793c24a1f4"
"f8aa201c-4ff1-45a4-890e-840d63459ca2"
"88ec040b-8705-4f77-8f41-f81e57632f7d"
"e0009214-c0a0-4a7b-96e2-d6a83e966ce0"
"577c946d-6de5-4b55-a854-cd3fde40bff2"
"4e6f083b-5b9a-4393-9890-2a83da8188f1"
"9c20a245-f2c0-43ae-82c9-2232ec6b594f"
```

**Comment by maximilianh** [comment] 2019-10-17 20:47
Sorry, I’m a user, not a DCP engineer. What is Azul again? Should I know?

**Comment by hannes-ucsc** [comment] 2019-10-17 22:13
> What is Azul again? 

Azul is the DataBrowser backend, or, what you referred to as the DataBowser API.

**Comment by matthewspeir** [comment] 2019-10-18 07:54
Thanks, @hannes-ucsc. Makes sense. I'll try to make a ticket for that in the matrix service repo soon (though I doubt it will be prioritized). In the meantime, it sounds like using Azul to get a list project UUIDs and then using this to download files from the project-assets/project-matrices directory is a suitable workaround.

**Comment by NoopDog** [comment] 2023-02-12 18:28
Resolved by workarund

**Closed as completed by NoopDog** 2023-02-12 18:28 UTC
