### ISSUE TITLE
FileTypeSummaries is only showing selected file types when a file type is selected. Instead it always needs to show all file types that have files.

### ISSUE THREAD

**Issue by NoopDog** [DataBiosphere/data-browser#262] opened 2018-10-12 17:52 UTC
https://service.dev.explore.data.humancellatlas.org/repository/summary/files?filters=%7B%22file%22:%7B%22fileFormat%22:%7B%22is%22:%5B%22bam%22%5D%7D%7D%7D

With bam selected only bam files are in the file type summary.

![Screen Shot 2018-10-13 at 3.48.28 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/91112954-2fdd-4a86-94f6-59c4ca12dc57)

Instead we need all file types that have a non zero count as in the fileType facet. We need to list what "could" be downloaded not what "will" be downloaded just like the file facets.

![Screen Shot 2018-10-13 at 3.51.40 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/a12bddc1-8a31-46fd-ba1c-c6b96fb1d373)

┆Issue Number: HCAB-233

**Comment by theathorn** [comment] 2018-10-17 23:39
Duplicate of #260.

**Closed as completed by theathorn** 2018-10-17 23:39 UTC
